# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHI_Building_Permits',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('permit', models.CharField(default=b'', max_length=255)),
                ('permit_type', models.CharField(default=b'', max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('street_number', models.CharField(default=b'', max_length=255)),
                ('street_direction', models.CharField(default=b'', max_length=255)),
                ('street_name', models.CharField(default=b'', max_length=255)),
                ('suffix', models.CharField(default=b'', max_length=255)),
                ('work_description', models.TextField(blank=True, default=b'', null=True)),
                ('pin1', models.CharField(default=b'', max_length=255)),
                ('latitude', models.CharField(default=b'', max_length=255)),
                ('longitude', models.CharField(default=b'', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CHIReporterBuildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('buildingFootprint', models.TextField(default=b'')),
                ('buildingAddress', models.CharField(default=b'', max_length=255)),
                ('buildingPIN', models.CharField(default=b'', max_length=255)),
                ('buildingStories', models.IntegerField(default=0)),
                ('approved', models.NullBooleanField(default=None)),
                ('description', models.TextField(blank=True, default=b'', null=True)),
                ('story1', models.URLField(blank=True, default=b'', max_length=1000, null=True)),
                ('story2', models.URLField(blank=True, default=b'', max_length=1000, null=True)),
                ('story3', models.URLField(blank=True, default=b'', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CHIskyline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('iDontSeeMyNeighborhood', models.BooleanField(default=False)),
                ('buildingFootprint', models.TextField(default=b'')),
                ('buildingAddress', models.CharField(default=b'', max_length=255)),
                ('buildingPIN', models.CharField(default=b'', max_length=255)),
                ('buildingStories', models.IntegerField(default=0)),
                ('approved', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='CHISponsoredBuildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('buildingFootprint', models.TextField(default=b'')),
                ('buildingName', models.CharField(default=b'', max_length=255)),
                ('buildingAddress', models.CharField(default=b'', max_length=255)),
                ('buildingText', models.CharField(default=b'', max_length=255)),
                ('buildingStories', models.IntegerField(default=0)),
                ('buildingImage', models.ImageField(upload_to=b'img/%Y_%m_%d_%h_%M_%s')),
            ],
        ),
        migrations.CreateModel(
            name='neighborhoodCHI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnaurl', models.CharField(default=b'', max_length=255)),
                ('name', models.CharField(default=b'', max_length=255)),
                ('county', models.CharField(default=b'', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chisponsoredbuildings',
            name='whereBuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skyline_chi.neighborhoodCHI'),
        ),
        migrations.AddField(
            model_name='chiskyline',
            name='whereBuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skyline_chi.neighborhoodCHI'),
        ),
        migrations.AddField(
            model_name='chireporterbuildings',
            name='whereBuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skyline_chi.neighborhoodCHI'),
        ),
    ]
