# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0002_auto_20160928_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chireporterbuildings',
            name='story2',
        ),
        migrations.RemoveField(
            model_name='chireporterbuildings',
            name='story3',
        ),
        migrations.AddField(
            model_name='chireporterbuildings',
            name='buildingImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'img/%Y_%m_%d_%h_%M_%s'),
        ),
        migrations.AddField(
            model_name='chireporterbuildings',
            name='projectName',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chireporterbuildings',
            name='zoning_pdfs',
            field=models.FileField(blank=True, null=True, upload_to=b'reporter_zoning_pdfs/'),
        ),
        migrations.AlterField(
            model_name='chireporterbuildings',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True),
        ),
    ]
