# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0004_chireporterbuildings_buildingzip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chireporterbuildings',
            name='buildingZip',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
