# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0005_auto_20161007_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chireporterbuildings',
            name='zoning_pdfs',
            field=models.URLField(blank=True, default=b'', max_length=1000, null=True),
        ),
    ]
