# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0007_auto_20161019_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='chi_building_permits',
            name='buildingImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'img/%Y_%m_%d_%h_%M_%s'),
        ),
        migrations.AddField(
            model_name='chi_building_permits',
            name='buildingZip',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chi_building_permits',
            name='projectName',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chi_building_permits',
            name='story1',
            field=models.URLField(blank=True, default=b'', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chi_building_permits',
            name='zoning_pdfs',
            field=models.URLField(blank=True, default=b'', max_length=1000, null=True),
        ),
    ]
