# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0008_auto_20161019_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='chi_building_permits',
            name='buildingAddress',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='chi_building_permits',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chi_building_permits',
            name='buildingZip',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
