# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0009_auto_20161019_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chi_building_permits',
            name='buildingZip',
        ),
        migrations.AddField(
            model_name='chi_building_permits',
            name='whereBuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skyline_chi.neighborhoodCHI'),
        ),
        migrations.AlterField(
            model_name='chi_building_permits',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
