# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0014_chi_building_permits_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_building_permits_new',
            name='ID_ODP',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
