# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0015_auto_20161028_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiskyline',
            options={'permissions': (('modify_UGC', 'Can add, edit, update, delete UCG buildings.'),)},
        ),
        migrations.AlterModelOptions(
            name='chisponsoredbuildings',
            options={'permissions': (('modify_sponsored', 'Can add, edit, update, delete sponsored buildings.'),)},
        ),
    ]
