# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 22:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline_chi', '0016_auto_20161101_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiskyline',
            name='buildingDoc',
            field=models.FileField(blank=True, null=True, upload_to=b'buildingDocs/'),
        ),
        migrations.AddField(
            model_name='chiskyline',
            name='buildingImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'img/%Y_%m_%d_%h_%M_%s'),
        ),
        migrations.AddField(
            model_name='chiskyline',
            name='buildingURL',
            field=models.URLField(blank=True, default=b'', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chiskyline',
            name='imageDocOrURL',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='chiskyline',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chiskyline',
            name='projectName',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chiskyline',
            name='userEmail',
            field=models.EmailField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chi_building_permits_new',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='chi_building_permits_old',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='chireporterbuildings',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='chiskyline',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='chisponsoredbuildings',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
