# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0014_auto_20160925_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nycreporterbuildings',
            name='description',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
