# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0017_nycreporterbuildings_buildingzip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nycreporterbuildings',
            name='zoning_pdfs',
            field=models.URLField(blank=True, default=b'', max_length=1000, null=True),
        ),
    ]
