# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0020_auto_20161019_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyc_dob_permit_issuance',
            name='buildingAddress',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='nyc_dob_permit_issuance',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nyc_dob_permit_issuance',
            name='whereBuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skyline.neighborhoodNYC'),
        ),
    ]
