# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0024_auto_20161024_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyc_dob_permit_issuance',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nycreporterbuildings',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nycsponsoredbuildings',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
