# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0025_auto_20161024_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyc_dob_permit_issuance',
            name='whereBuilding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skyline.neighborhoodNYC'),
        ),
    ]
