# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0027_auto_20161101_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhoodnyc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nycskyline',
            options={'permissions': (('modify_UGC', 'Can add, edit, update, delete UCG buildings.'),)},
        ),
    ]
