# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0028_auto_20161101_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='nycskyline',
            name='buildingDoc',
            field=models.FileField(blank=True, null=True, upload_to=b'buildingDocs/'),
        ),
        migrations.AddField(
            model_name='nycskyline',
            name='buildingImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'img/%Y_%m_%d_%h_%M_%s'),
        ),
        migrations.AddField(
            model_name='nycskyline',
            name='buildingURL',
            field=models.URLField(blank=True, default=b'', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='nycskyline',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nycskyline',
            name='projectName',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nycskyline',
            name='userEmail',
            field=models.EmailField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
