# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0029_auto_20161114_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='nycskyline',
            name='imageDocOrURL',
            field=models.BooleanField(default=False),
        ),
    ]
