# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0030_nycskyline_imagedocorurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nycskyline',
            name='imageDocOrURL',
            field=models.NullBooleanField(default=None),
        ),
    ]
