# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 00:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0032_auto_20161121_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyc_dob_permit_issuance',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='nycreporterbuildings',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='nycskyline',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='nycsponsoredbuildings',
            name='buildingStories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
