# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyline', '0034_remove_nycskyline_idontseemyneighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyc_dob_permit_issuance',
            name='zoning_pdfs',
            field=models.URLField(blank=True, default=b'', max_length=1000, null=True),
        ),
    ]
