from django.db import models
from django import forms

# import all crimemaps models
from crimemaps.models import *

# crimemaps forms below

YEAR_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
    ('31', '31'),
    ('32', '32'),
    ('33', '33'),
    ('34', '34'),
    ('35', '35'),
    ('36', '36'),
    ('37', '37'),
    ('38', '38'),
    ('39', '39'),
    ('40', '40'),
    ('41', '41'),
    ('42', '42'),
    ('43', '43'),
    ('44', '44'),
    ('45', '45'),
    ('46', '46'),
    ('47', '47'),
    ('48', '48'),
    ('49', '49'),
    ('50', '50'),
)


NYC_NEIGHBORHOOD_CHOICES = (
    ('allerton', 'Allerton'),
    ('annandale', 'Annandale'),
    ('arden-heights', 'Arden Heights'),
    ('arrochar', 'Arrochar'),
    ('arverne', 'Arverne'),
    ('astoria', 'Astoria'),
    ('auburndale', 'Auburndale'),
    ('bath-beach', 'Bath Beach'),
    ('battery-park-city', 'Battery Park City'),
    ('bay-ridge', 'Bay Ridge'),
    ('bay-terrace', 'Bay Terrace'),
    ('bay-terrace-staten-island', 'Bay Terrace (Staten Island)'),
    ('baychester', 'Baychester'),
    ('bayside', 'Bayside'),
    ('bayswater', 'Bayswater'),
    ('bed-stuy', 'Bedford Stuyvesant'),
    ('bedford-park', 'Bedford Park'),
    ('beechhurst', 'Beechhurst'),
    ('belle-harbor', 'Belle Harbor'),
    ('bellerose', 'Bellerose'),
    ('belmont', 'Belmont'),
    ('bensonhurst', 'Bensonhurst'),
    ('bergen-beach', 'Bergen Beach'),
    ('bloomfield', 'bloomfield'),
    ('boerum-hill', 'Boerum Hill'),
    ('borough-park', 'Borough Park'),
    ('breezy-point', 'Breezy Point'),
    ('briarwood', 'Briarwood'),
    ('brighton-beach', 'Brighton Beach'),
    ('broad-channel', 'Broad Channel'),
    ('brooklyn-heights', 'Brooklyn Heights'),
    ('brookville', 'Brookville'),
    ('brownsville', 'Brownsville'),
    ('bulls-heads', 'Bulls Heads'),
    ('bushwick', 'Bushwick'),
    ('cambria-heights', 'Cambria Heights'),
    ('canarsie', 'Canarsie'),
    ('carnegie-hill', 'Carnegie Hill'),
    ('carroll-gardens', 'Carroll Gardens'),
    ('castle-hill', 'Castle Hill'),
    ('castleton-corners', 'Castleton Corners'),
    ('central-harlem', 'Central Harlem'),
    ('charleston', 'Charleston'),
    ('chelsea', 'Chelsea'),
    ('chelsea-staten-island', 'Chelsea (Staten Island)'),
    ('chinatown', 'Chinatown'),
    ('city-island', 'City Island'),
    ('civic-center', 'Civic Center'),
    ('claremont', 'Claremont'),
    ('claremont-village', 'Claremont Village'),
    ('clason-point', 'Clason Point'),
    ('clifton', 'Clifton'),
    ('clinton-hill', 'Clinton Hill'),
    ('co-op-city', 'Co-Op City'),
    ('cobble-hill', 'Cobble Hill'),
    ('college-point', 'College Point'),
    ('columbia-street-waterfront-district', 'Columbia Street Waterfront District'),
    ('columbus-circle', 'Coumbus Circle'),
    ('concord', 'Concord'),
    ('concourse', 'Concourse'),
    ('concourse-village', 'Concourse Village'),
    ('coney-island', 'Coney Island'),
    ('corona', 'Corona'),
    ('country-club', 'Country Club'),
    ('crown-heights', 'Crown Heights'),
    ('cypress-hills', 'Cypress Hills'),
    ('ditmars', 'Ditmars'),
    ('ditmas-park', 'Ditmas Park'),
    ('dongan-hills', 'Dongan Hills'),
    ('douglaston', 'Douglaston'),
    ('downtown-brooklyn', 'Downtown Brooklyn'),
    ('dumbo', 'Dumbo'),
    ('dyker-heights', 'Dyker Heights'),
    ('east-elmhurst', 'East Elmhurst'),
    ('east-flatbush', 'East Flatbush'),
    ('east-harlem', 'East Harlem'),
    ('east-new-york', 'East New York'),
    ('east-village', 'East Village'),
    ('east-williamsburg', 'East Williamsburg'),
    ('eastchester', 'Eastchester'),
    ('edenwald', 'Edenwald'),
    ('edgemere', 'Edgemere'),
    ('elm-park', 'Elm Park'),
    ('elmhurst', 'Elmhurst'),
    ('eltingville', 'Eltingville'),
    ('emerson-hill', 'Emerson Hill'),
    ('far-rockaway', 'Far Rockaway'),
    ('fieldston', 'Fieldston'),
    ('financial-district', 'Financial District'),
    ('flatbush', 'Flatbush'),
    ('flatiron', 'Flatiron'),
    ('flatlands', 'Flatlands'),
    ('flushing', 'Flushing'),
    ('fordham', 'Fordham'),
    ('forest-hills', 'Forest Hills'),
    ('fort-george', 'Fort George'),
    ('fort-greene', 'Fort Greene'),
    ('fort-hamilton', 'Fort Hamilton'),
    ('fort-wadsworth', 'Fort Wadsworth'),
    ('fresh-meadows', 'Fresh Meadows'),
    ('garment-district', 'Garment District'),
    ('gerritsen-beach', 'Gerritsen Beach'),
    ('glendale', 'Glendale'),
    ('governors-island', 'Governors Island'),
    ('gowanus', 'Gowanus'),
    ('gramercy', 'Gramercy'),
    ('graniteville', 'Graniteville'),
    ('grant-city', 'Grant City'),
    ('grasmere', 'Grasmere'),
    ('gravesend', 'Gravesend'),
    ('great-kills', 'Great Kills'),
    ('greenpoint', 'Greenpoint'),
    ('greenridge', 'Greenridge'),
    ('greenwich-village', 'Greenwich Village'),
    ('greenwood-heights', 'Greenwood Heights'),
    ('grymes-hill', 'Grymes Hill'),
    ('hamilton-beach', 'Hamilton Beach'),
    ('hamilton-heights', 'Hamilton Heights'),
    ('heartland-village', 'Heartland Village'),
    ('hells-kitchen-clinton', 'Hell\'s Kitchen / Clinton'),
    ('high-bridge', 'High Bridge'),
    ('hillcrest', 'Hillcrest'),
    ('hollis', 'Hollis'),
    ('holliswood', 'Holliswood'),
    ('homecrest', 'Homecrest'),
    ('howard-beach', 'Howard Beach'),
    ('hudson-heights', 'Hudson Heights'),
    ('hudson-square', 'Hudson Square'),
    ('huguenot', 'Huguenot'),
    ('hunts-point', 'Hunt\'s Point'),
    ('inwood', 'Inwood'),
    ('jackson-heights', 'Jackson Heights'),
    ('jamaica', 'Jamaica'),
    ('jamaica-estates', 'Jamaica Estates'),
    ('jamaica-hills', 'Jamaica Hills'),
    ('kensington', 'Kensington'),
    ('kew-gardens', 'Kew Gardens'),
    ('kew-gardens-hills', 'Kew Gardens Hills'),
    ('kingsbridge', 'Kingsbridge'),
    ('kingsbridge-heights', 'Kingsbridge Heights'),
    ('kips-bay', 'Kips Bay'),
    ('laurelton', 'Laurelton'),
    ('lenox-hill', 'Lenox Hill'),
    ('lighthouse-hills', 'Lighthouse Hills'),
    ('lincoln-square', 'Lincoln Square'),
    ('lindenwood', 'Lindenwood'),
    ('little-italy', 'Little Italy'),
    ('little-neck', 'Little Neck'),
    ('livingston', 'Livingston'),
    ('long-island-city', 'Long Island City'),
    ('longwood', 'Longwood'),
    ('lower-east-side', 'Lower East Side'),
    ('malba', 'Malba'),
    ('manhattan-beach', 'Manhattan Beach'),
    ('manhattan-valley', 'Manhattan Valley'),
    ('marble-hill', 'Marble Hill'),
    ('marine-park', 'Marine Park'),
    ('mariners-harbor', 'Mariner\'s Harbor'),
    ('maspeth', 'Maspeth'),
    ('meatpacking-district', 'Meatpacking District'),
    ('meiers-corners', 'Meier\'s Corners'),
    ('melrose', 'Melrose'),
    ('middle-village', 'Middle Village'),
    ('midland-beach', 'Midland Beach'),
    ('midtown', 'Midtown'),
    ('midtown-east', 'Midtown East'),
    ('midtown-south', 'Midtown South'),
    ('midwood', 'Midwood'),
    ('mill-basin', 'Mill Basin'),
    ('morningside-heights', 'Morningside Heights'),
    ('morris-heights', 'Morris Heights'),
    ('morris-park', 'Morris Park'),
    ('morrisania', 'Morrisania'),
    ('mott-haven', 'Mott Haven'),
    ('mount-hope', 'Mount Hope'),
    ('murray-hill', 'Murray Hill'),
    ('murray-hill-queens', 'Murray Hill (Queens)'),
    ('navy-yard', 'Navy Yard'),
    ('neponsit', 'Neponsit'),
    ('new-brighton', 'New Brighton'),
    ('new-dorp', 'New Dorp'),
    ('new-dorp-beach', 'New Dorp Beach'),
    ('new-springville', 'New Springville'),
    ('noho', 'NoHo'),
    ('nolita', 'Nolita'),
    ('norwood', 'Norword'),
    ('oakland-gardens', 'Oakland Gardens'),
    ('oakwood', 'Oakwood'),
    ('ocean-breeze', 'Ocean Breeze'),
    ('ocean-hill', 'Ocean Hill'),
    ('old-town', 'Old Town'),
    ('olinville', 'Olinville'),
    ('ozone-park', 'Ozone Park'),
    ('park-slope', 'Park Slope'),
    ('parkchester', 'Parkchester'),
    ('pelham-bay', 'Pelham Bay'),
    ('pelham-gardens', 'Pelham Gardens'),
    ('pelham-parkway', 'Pelham Parkway'),
    ('pleasant-plains', 'Pleasant Plains'),
    ('pomonok', 'Pomonok'),
    ('port-morris', 'Port Morris'),
    ('port-richmond', 'Port Richmond'),
    ('princes-bay', 'Prince\'s Bay'),
    ('prospect-heights', 'Prospect Heights'),
    ('prospect-park-south', 'Prospect Park South'),
    ('prospect-lefferts-gardens', 'Prospect Lefferts Gardens'),
    ('queens-village', 'Queens Village'),
    ('randall-manor', 'Randall Manor'),
    ('randalls-island', 'Randall\'s Island'),
    ('red-hook', 'Red Hook'),
    ('rego-park', 'Rego Park'),
    ('richmond-hill', 'Richmond Hill'),
    ('richmond-town', 'Richmond Town'),
    ('ridgewood', 'Ridgewood'),
    ('riverdale', 'Riverdale'),
    ('rochdale-village', 'Rochdale Village'),
    ('rockaway-beach', 'Rockaway Beach'),
    ('rockaway-park', 'Rockaway Park'),
    ('roosevelt-island', 'Roosevelt Island'),
    ('rosebank', 'rosebank'),
    ('rosedale', 'Rosedale'),
    ('rossville', 'Rossville'),
    ('roxbury', 'Roxbury'),
    ('schuylerville', 'Schuylerville'),
    ('sea-gate', 'Sea Gate'),
    ('seaside', 'Seaside'),
    ('sheepshead-bay', 'Sheepshead Bay'),
    ('shore-acres', 'Shore Acres'),
    ('silver-lake', 'Silver Lake'),
    ('soho', 'SoHo'),
    ('soundview', 'Soundview'),
    ('south-beach', 'South Beach'),
    ('south-jamaica', 'South Jamaica'),
    ('south-ozone-park', 'South Ozone Park'),
    ('south-street-seaport', 'South Street Seaport'),
    ('springfield-gardens', 'Springfield Gardens'),
    ('spuyten-duyvil', 'Spuyten Duyvil'),
    ('st-albans', 'St. Albans'),
    ('st.-george', 'St. George'),
    ('stapleton', 'Stapleton'),
    ('starrett-city', 'Starrett City'),
    ('stuy-town', 'Stuyvesant Town'),
    ('sugar-hill', 'Sugar Hill'),
    ('sunnyside', 'Sunnyside'),
    ('sunnyside-staten-island', 'Sunnyside (Staten Island)'),
    ('sunset-park', 'Sunset Park'),
    ('sutton-place', 'Sutton Place'),
    ('throgs-neck', 'Throgs Neck'),
    ('times-square-theater-district', 'Times Square / Theater District'),
    ('todt-hill', 'Todt Hill'),
    ('tompkinsville', 'Tompkinsville'),
    ('tottenville', 'Tottenville'),
    ('travis', 'Travis'),
    ('tremont-east-tremont', 'Tremont / East Tremont'),
    ('tribeca', 'Tribeca'),
    ('turtle-bay', 'Turtle Bay'),
    ('union-square', 'Union Square'),
    ('unionport', 'Unionport'),
    ('university-heights', 'University Heights'),
    ('upper-east-side', 'Upper East Side'),
    ('upper-west-side', 'Upper West Side'),
    ('utopia', 'Utopia'),
    ('van-nest', 'Van Nest'),
    ('vinegar-hill', 'Vinegar Hill'),
    ('wakefield', 'Wakefield'),
    ('washington-heights', 'Washington Heights'),
    ('wavecrest', 'Wavecrest'),
    ('west-brighton', 'West Brighton'),
    ('west-farms', 'West Farms'),
    ('west-harlem', 'West Harlem'),
    ('west-village', 'West Village'),
    ('westchester-square', 'Westchester Square'),
    ('westerleigh', 'Westerleigh'),
    ('whitestone', 'Whitestone'),
    ('willets-point', 'Willet\'s Point'),
    ('williamsbridge', 'Williamsbridge'),
    ('williamsburg', 'Williamsburg'),
    ('willowbrook', 'Willowbrook'),
    ('windsor-terrace', 'Windsor Terrace'),
    ('woodhaven', 'Woodhaven'),
    ('woodlawn', 'Woodlawn'),
    ('woodrow', 'Woodrow'),
    ('woodside', 'Woodside'),
    ('yorkville', 'Yorkville'),
)


CHI_NEIGHBORHOOD_CHOICES = (
    ('austin', 'Austin'),
    ('albany-park', 'Albany Park'),
    ('altgeld-gardens', 'Altgeld Gardens'),
    ('andersonville', 'Andersonville'),
    ('archer-heights', 'Archer Heights'),
    ('armour-square', 'Armour Square'),
    ('ashburn', 'Ashburn'),
    ('auburn-gresham', 'Auburn Gresham'),
    ('avalon-park', 'Avalon Park'),
    ('avondale', 'Avondale'),
    ('back-of-yards', 'Back of Yards'),
    ('belmont-cragin', 'Belmont Cragin'),
    ('beverly', 'Beverly'),
    ('boystown', 'Boystown'),
    ('brainerd', 'Brainerd'),
    ('bridgeport', 'Bridgeport'),
    ('brighton-park', 'Brighton Park'),
    ('bronzeville', 'Bronzeville'),
    ('bucktown', 'Bucktown'),
    ('burnside', 'Burnside'),
    ('bush', 'Bush'),
    ('calumet-heights', 'Calumet Heights'),
    ('canaryville', 'Canaryville'),
    ('chatham', 'Chatham'),
    ('chicago-lawn', 'Chicago Lawn'),
    ('chinatown', 'Chinatown'),
    ('clearing', 'Clearing'),
    ('douglas', 'Douglas'),
    ('downtown', 'Downtown'),
    ('dunning', 'Dunning'),
    ('east-garfield-park', 'East Garfield Park'),
    ('east-side', 'East Side'),
    ('east-village', 'East Village'),
    ('edgebrook', 'Edgebrook'),
    ('edgewater', 'Edgewater'),
    ('edison-park', 'Edison Park'),
    ('englewood', 'Englewood'),
    ('ford-city', 'Ford City'),
    ('forest-glen', 'Forest Glen'),
    ('fuller-park', 'Fuller Park'),
    ('gage-park', 'Gage Park'),
    ('gap', 'Gap'),
    ('garfield-park', 'Garfield Park'),
    ('garfield-ridge', 'Garfield Ridge'),
    ('gladstone-park', 'Gladstone Park'),
    ('gold-coast', 'Gold Coast'),
    ('grand-boulevard', 'Grand Boulevard'),
    ('grand-crossing', 'Grand Crossing'),
    ('greektown', 'Greektown'),
    ('heart-of-chicago', 'Heart of Chicago'),
    ('heart-of-italy', 'Heart of Italy'),
    ('hegewisch', 'Hegewisch'),
    ('hermosa', 'Hermosa'),
    ('humboldt-park', 'Humboldt Park'),
    ('hyde-park', 'Hyde Park'),
    ('irving-park', 'Irving Park'),
    ('jackson-highlands', 'Jackson Highlands'),
    ('jefferson-park', 'Jefferson Park'),
    ('kenwood', 'Kenwood'),
    ('lakeview', 'Lakeview'),
    ('lincoln-park', 'Lincoln Park'),
    ('lincoln-square', 'Lincoln Square'),
    ('little-italy', 'Little Italy'),
    ('little-village', 'Little Village'),
    ('logan-square', 'Logan Square'),
    ('loop', 'Loop'),
    ('marquette-park', 'Marquette Park'),
    ('mayfair', 'Mayfair'),
    ('mckinley-park', 'McKinley Park'),
    ('medical-district', 'Medical District'),
    ('midway', 'Midway'),
    ('montclare', 'Montclare'),
    ('morgan-park', 'Morgan Park'),
    ('mt-greenwood', 'Mt. Greenwood'),
    ('near-west-side', 'Near West Side'),
    ('new-city', 'New City'),
    ('noble-square', 'Noble Square'),
    ('north-center', 'North Center'),
    ('north-edgebrook', 'North Edgebrook'),
    ('north-lawndale', 'North Lawndale'),
    ('north-park', 'North Park'),
    ('norwood-park', 'Norwood Park'),
    ('oakland', 'Oakland'),
    ('ohare', 'O\'Hare'),
    ('old-edgebrook', 'Old Edgebrook'),
    ('old-town', 'Old Town'),
    ('pill-hill', 'Pill Hill'),
    ('pilsen', 'Pilsen'),
    ('portage-park', 'Portage Park'),
    ('pullman', 'Pullman'),
    ('ravenswood-manor', 'Ravenswood Manor'),
    ('ravenswood', 'Ravenswood'),
    ('river-north', 'River North'),
    ('river-west', 'River West'),
    ('riverdale', 'Riverdale'),
    ('rogers-park', 'Roger\'s Park'),
    ('roscoe-village', 'Roscoe Village'),
    ('roseland', 'Roseland'),
    ('sauganash', 'Sauganash'),
    ('south-austin', 'South Austin'),
    ('south-chicago', 'South Chicago'),
    ('south-deering', 'South Deering'),
    ('south-lawndale', 'South Lawndale'),
    ('south-loop', 'South Loop'),
    ('south-shore-above-79th', 'South Shore above 79th'),
    ('south-shore', 'South Shore'),
    ('streeterville', 'Streeterville'),
    ('tri-taylor', 'Tri Taylor'),
    ('ukrainian-village', 'Ukrainian Village'),
    ('university-village', 'University Village'),
    ('uptown', 'Uptown'),
    ('washington-heights', 'Washington Heights'),
    ('washington-park', 'Washington Park'),
    ('west-beverly', 'West Beverly'),
    ('west-elsdon', 'West Elsdon'),
    ('west-englewood', 'West Englewood'),
    ('west-humboldt-park', 'West Humboldt Park'),
    ('west-lawn', 'West Lawn'),
    ('west-loop', 'West Loop'),
    ('west-pullman', 'West Pullman'),
    ('west-ridge', 'West Ridge'),
    ('west-rogers-park', 'West Roger\'s Park'),
    ('west-town', 'West Town'),
    ('wicker-park', 'Wicker Park'),
    ('woodlawn', 'Woodlawn'),
    ('wrigleyville', 'Wrigleyville'),
)


class nycNeighDrawForm(forms.ModelForm):
    neighborhoodLive = forms.ChoiceField(choices=NYC_NEIGHBORHOOD_CHOICES, label="Please select the neighborhood in which you currently live.")
    yearsLived = forms.ChoiceField(choices=YEAR_CHOICES, label="How long have you lived in this neighborhood?")

    class Meta:
        model = neighborhoodDraw
        fields = ('neighborhoodLive', 'yearsLived')



