

YEAR_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
    ('31', '31'),
    ('32', '32'),
    ('33', '33'),
    ('34', '34'),
    ('35', '35'),
    ('36', '36'),
    ('37', '37'),
    ('38', '38'),
    ('39', '39'),
    ('40', '40'),
    ('41', '41'),
    ('42', '42'),
    ('43', '43'),
    ('44', '44'),
    ('45', '45'),
    ('46', '46'),
    ('47', '47'),
    ('48', '48'),
    ('49', '49'),
    ('50', '50'),
)


NYC_NEIGHBORHOOD_CHOICES = (
    ('allerton', 'Allerton-Pelham Gardens'),
    ('annandale', 'Annadale-Huguenot-Prince\'s Bay-Eltingville'),
    ('arden-heights', 'Arden Heights'),
    ('astoria', 'Astoria'),
    ('auburndale', 'Auburndale'),
    ('baisley-park', 'Baisley Park'),
    ('bath-beach', 'Bath Beach'),
    ('battery-park-city', 'Battery Park City-Lower Manhattan'),
    ('bay-ridge', 'Bay Ridge'),
    ('bayside', 'Bayside-Bayside Hills'),
    ('bedford', 'Bedford'),
    ('bedford-park', 'Bedford Park-Fordham North'),
    ('belle-harbor', 'Breezy Point-Belle Harbor-Rockaway Park-Broad Channel'),
    ('bellerose', 'Bellerose'),
    ('belmont', 'Belmont'),
    ('bensonhurst-east', 'Bensonhurst East'),
    ('bensonhurst-west', 'Bensonhurst West'),
    ('borough-park', 'Borough Park'),
    ('briarwood', 'Briarwood-Jamaica Hills'),
    ('brighton-beach', 'Brighton Beach'),
    ('bronxdale', 'Bronxdale'),
    ('brooklyn-heights', 'Brooklyn Heights-Cobble Hill'),
    ('brownsville', 'Brownsville'),
    ('bulls-heads', 'Bulls Heads'),
    ('bushwick-north', 'Bushwick North'),
    ('bushwick-south', 'Bushwick South'),
    ('cambria-heights', 'Cambria Heights'),
    ('canarsie', 'Canarsie'),
    ('carroll-gardens', 'Carroll Gardens-Columbia Street-Red Hook'),
    ('central-harlem', 'Central Harlem North-Polo Grounds'),
    ('central-harlem-south', 'Central Harlem South'),
    ('charleston', 'Charleston-Richmond Valley-Tottenville'),
    ('chinatown', 'Chinatown'),
    ('claremont', 'Claremont-Bathgate'),
    ('hells-kitchen-clinton', 'Clinton'),
    ('clinton-hill', 'Clinton Hill'),
    ('co-op-city', 'Co-op City'),
    ('college-point', 'College Point'),
    ('corona', 'Corona'),
    ('crotona-park-east', 'Crotona Park East'),
    ('country-club', 'Country Club'),
    ('crown-heights-north', 'Crown Heights North'),
    ('crown-heights-south', 'Crown Heights South'),
    ('cypress-hills', 'Cypress Hills-City Line'),
    ('douglaston', 'Douglas Manor-Douglaston-Little Neck'),
    ('downtown-brooklyn', 'DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill'),
    ('dyker-heights', 'Dyker Heights'),
    ('concourse', 'East Concourse-Concourse Village'),
    ('east-elmhurst', 'East Elmhurst'),
    ('east-flatbush', 'East Flatbush-Farragut'),
    ('east-flushing', 'East Flushing'),
    ('east-harlem-north', 'East Harlem North'),
    ('east-harlem-south', 'East Harlem South'),
    ('east-new-york', 'East New York'),
    ('tremont-east-tremont', 'East Tremont'),
    ('east-village', 'East Village'),
    ('east-williamsburg', 'East Williamsburg'),
    ('baychester', 'Eastchester-Edenwald-Baychester'),
    ('elmhurst', 'Elmhurst'),
    ('erasmus', 'Erasmus'),
    ('bayswater', 'Far Rockaway-Bayswater'),
    ('flatbush', 'Flatbush'),
    ('flatlands', 'Flatlands'),
    ('flushing', 'Flushing'),
    ('fordham', 'Fordham South'),
    ('forest-hills', 'Forest Hills'),
    ('fort-greene', 'Fort Greene'),
    ('bay-terrace', 'Ft. Totten-Bay Terrace-Clearview'),
    ('fresh-meadows', 'Fresh Meadows-Utopia'),
    ('garment-district', 'Garment District'),
    ('bergen-beach', 'Georgetown-Marine Park-Bergen Beach-Mill Basin'),
    ('gerritsen-beach', 'Gerritsen Beach'),
    ('glendale', 'Glendale'),
    ('glen-oaks','Glen Oaks-Floral Park-New Hyde Park'),
    ('gramercy', 'Gramercy'),
    ('arrochar', 'Grasmere-Arrochar-Ft. Wadsworth'),
    ('gravesend', 'Gravesend'),
    ('great-kills', 'Great Kills'),
    ('greenpoint', 'Greenpoint'),
    ('grymes-hill', 'Grymes Hill-Clifton-Fox Hills'),
    ('hamilton-heights', 'Hamilton Heights'),
    ('arverne', 'Hammels-Arverne-Edgemere'),
    ('high-bridge', 'Highbridge'),
    ('hollis', 'Hollis'),
    ('homecrest', 'Homecrest'),
    ('chelsea', 'Hudson Yards-Chelsea-Flatiron-Union Square'),
    ('sunnyside', 'Hunters Point-Sunnyside-West Maspeth'),
    ('hunts-point', 'Hunts Point'),
    ('jackson-heights', 'Jackson Heights'),
    ('jamaica', 'Jamaica'),
    ('jamaica-estates', 'Jamaica Estates-Holliswood'),
    ('kensington', 'Kensington-Ocean Parkway'),
    ('kew-gardens', 'Kew Gardens'),
    ('kew-gardens-hills', 'Kew Gardens Hills'),
    ('kingsbridge-heights', 'Kingsbridge Heights'),
    ('laurelton', 'Laurelton'),
    ('lenox-hill', 'Lenox Hill-Roosevelt Island'),
    ('lincoln-square', 'Lincoln Square'),
    ('lindenwood', 'Lindenwood-Howard Beach'),
    ('longwood', 'Longwood'),
    ('lower-east-side', 'Lower East Side'),
    ('madison', 'Madison'),
    ('manhattanville', 'Manhattanville'),
    ('marble-hill', 'Marble Hill-Inwood'),
    ('marine-park', 'Marine Park'),
    ('mariners-harbor', 'Mariner\'s Harbor-Arlington-Port Ivory-Graniteville'),
    ('maspeth', 'Maspeth'),
    ('melrose', 'Melrose South-Mott Haven North'),
    ('middle-village', 'Middle Village'),
    ('midtown', 'Midtown-Midtown South'),
    ('midwood', 'Midwood'),
    ('morningside-heights', 'Morningside Heights'),
    ('morrisania', 'Morrisania-Melrose'),
    ('mott-haven', 'Mott Haven-Port Morris'),
    ('mount-hope', 'Mount Hope'),
    ('murray-hill', 'Murray Hill-Kips Bay'),
    ('murray-hill-queens', 'Murray Hill'),
    ('new-brighton', 'New Brighton-Silver Lake'),
    ('new-dorp', 'New Dorp-Midland Beach'),
    ('new-springville', 'New Springville-Bloomfield-Travis'),
    ('fieldston', 'North Riverdale-Fieldston-Riverdale'),
    ('norwood', 'Norword'),
    ('north-corona', 'North Corona'),
    ('north-side-south-side', 'North Side-South Side'),
    ('oakland-gardens', 'Oakland Gardens'),
    ('oakwood', 'Oakwood-Oakwood Beach'),
    ('ocean-hill', 'Ocean Hill'),
    ('ocean-parkway-south', 'Ocean Parkway South'),
    ('old-astoria', 'Old Astoria'),
    ('old-town', 'Old Town-Dongan Hills-South Beach'),
    ('ozone-park', 'Ozone Park'),
    ('park-slope', 'Park Slope-Gowanus'),
    ('parkchester', 'Parkchester'),
    ('pelham-bay', 'Pelham Bay-Country Club-City Island'),
    ('pelham-parkway', 'Pelham Parkway'),
    ('pomonok', 'Pomonok-Flushing Heights-Hillcrest'),
    ('port-richmond', 'Port Richmond'),
    ('prospect-heights', 'Prospect Heights'),
    ('prospect-lefferts-gardens', 'Prospect Lefferts Gardens-Wingate'),
    ('queensboro-hill', 'Queensboro Hill'),
    ('queens-village', 'Queens Village'),
    ('long-island-city', 'Queensbridge-Ravenswood-Long Island City'),    
    ('rego-park', 'Rego Park'),
    ('richmond-hill', 'Richmond Hill'),
    ('ridgewood', 'Ridgewood'),
    ('rosedale', 'Rosedale'),
    ('rossville', 'Rossville-Woodrow'),
    ('rugby', 'Rugby-Remsen Village'),
    ('schuylerville', 'Schuylerville-Throgs Neck-Edgewater Park'),
    ('sea-gate', 'Seagate-Coney Island'),
    ('sheepshead-bay', 'Sheepshead Bay-Gerritsen Beach-Manhattan Beach'),
    ('soho', 'SoHo-TriBeCa-Civic Center-Little Italy'),
    ('soundview', 'Soundview-Bruckner'),
    ('castle-hill', 'Soundview-Castle Hill-Clason Point-Harding Park'),
    ('south-jamaica', 'South Jamaica'),
    ('south-ozone-park', 'South Ozone Park'),
    ('springfield-gardens', 'Springfield Gardens North'),
    ('brookville', 'Springfield Gardens South-Brookville'),
    ('spuyten-duyvil', 'Spuyten Duyvil-Kingsbridge'),
    ('st-albans', 'St. Albans'),
    ('stapleton', 'Stapleton-Rosebank'),
    ('starrett-city', 'Starrett City'),
    ('steinway', 'Steinway'),
    ('stuy-heights', 'Stuyvesant Heights'),
    ('stuy-town', 'Stuyvesant Town-Cooper Village'),
    ('sunset-park-east', 'Sunset Park East'),
    ('sunset-park-west', 'Sunset Park West'),
    ('todt-hill', 'Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill'),
    ('turtle-bay', 'Turtle Bay-East Midtown'),
    ('university-heights', 'University Heights-Morris Heights'),
    ('upper-east-side', 'Upper East Side-Carnegie Hill'),
    ('upper-west-side', 'Upper West Side'),
    ('van-cortlandt-village', 'Van Cortlandt Village'),
    ('van-nest', 'Van Nest-Morris Park-Westchester Square'),
    ('washington-heights-north', 'Washington Heights North'),
    ('washington-heights-south', 'Washington Heights South'),
    ('west-brighton', 'West Brighton'),
    ('west-concourse', 'West Concourse'),
    ('west-farms', 'West Farms-Bronx River'),
    ('st.-george', 'West New Brighton-New Brighton-St. George'),
    ('west-village', 'West Village'),
    ('unionport', 'Westchester-Unionport'),
    ('westerleigh', 'Westerleigh'),
    ('whitestone', 'Whitestone'),
    ('williamsbridge', 'Williamsbridge-Olinville'),
    ('williamsburg', 'Williamsburg'),
    ('windsor-terrace', 'Windsor Terrace'),
    ('woodhaven', 'Woodhaven'),
    ('woodlawn', 'Woodlawn-Wakefield'),
    ('woodside', 'Woodside'),
    ('yorkville', 'Yorkville'),
)


CHI_NEIGHBORHOOD_CHOICES = (
    ('austin', 'Austin'),
    ('albany-park', 'Albany Park'),
    ('archer-heights', 'Archer Heights'),
    ('armour-square', 'Armour Square'),
    ('ashburn', 'Ashburn'),
    ('auburn-gresham', 'Auburn Gresham'),
    ('avalon-park', 'Avalon Park'),
    ('avondale', 'Avondale'),
    ('belmont-cragin', 'Belmont Cragin'),
    ('beverly', 'Beverly'),
    ('bridgeport', 'Bridgeport'),
    ('brighton-park', 'Brighton Park'),
    ('burnside', 'Burnside'),
    ('calumet-heights', 'Calumet Heights'),
    ('chatham', 'Chatham'),
    ('chicago-lawn', 'Chicago Lawn'),
    ('clearing', 'Clearing'),
    ('douglas', 'Douglas (Bronzeville)'),
    ('dunning', 'Dunning'),
    ('east-garfield-park', 'East Garfield Park'),
    ('east-side', 'East Side'),
    ('edgewater', 'Edgewater'),
    ('edison-park', 'Edison Park'),
    ('englewood', 'Englewood'),
    ('forest-glen', 'Forest Glen'),
    ('fuller-park', 'Fuller Park'),
    ('gage-park', 'Gage Park'),
    ('garfield-park', 'West Garfield Park'),
    ('garfield-ridge', 'Garfield Ridge'),
    ('grand-boulevard', 'Grand Boulevard (Bronzeville)'),
    ('grand-crossing', 'Greater Grand Crossing'),
    ('hegewisch', 'Hegewisch'),
    ('hermosa', 'Hermosa'),
    ('humboldt-park', 'Humboldt Park'),
    ('hyde-park', 'Hyde Park'),
    ('irving-park', 'Irving Park'),
    ('jefferson-park', 'Jefferson Park'),
    ('kenwood', 'Kenwood'),
    ('lakeview', 'Lakeview'),
    ('lincoln-park', 'Lincoln Park'),
    ('lincoln-square', 'Lincoln Square'),
    ('little-village', 'Little Village'),
    ('logan-square', 'Logan Square'),
    ('loop', 'Loop'),    
    ('mckinley-park', 'McKinley Park'),
    ('montclare', 'Montclare'),
    ('morgan-park', 'Morgan Park'),
    ('mt-greenwood', 'Mount Greenwood'),
    ('near-north-side', 'Near North Side'),
    ('near-west-side', 'Near West Side'),
    ('new-city', 'New City (Back of the Yards and Canaryville)'),
    ('north-center', 'North Center'),
    ('north-lawndale', 'North Lawndale'),
    ('north-park', 'North Park'),
    ('norwood-park', 'Norwood Park'),
    ('oakland', 'Oakland'),
    ('ohare', 'O\'Hare'),
    ('pilsen', 'Pilsen'),
    ('portage-park', 'Portage Park'),
    ('pullman', 'Pullman'),
    ('riverdale', 'Riverdale'),
    ('rogers-park', 'Rogers Park'),
    ('roseland', 'Roseland'),
    ('south-chicago', 'South Chicago'),
    ('south-deering', 'South Deering'),
    ('south-loop', 'South Loop'),
    ('south-shore', 'South Shore'),
    ('uptown', 'Uptown'),
    ('washington-heights', 'Washington Heights'),
    ('washington-park', 'Washington Park'),
    ('west-elsdon', 'West Elsdon'),
    ('west-englewood', 'West Englewood'),
    ('west-lawn', 'West Lawn'),
    ('west-pullman', 'West Pullman'),
    ('west-ridge', 'West Ridge'),
    ('west-town', 'West Town'),
    ('woodlawn', 'Woodlawn'),
)

